package com.feature.auction.domain

enum class Country(val code: String, val dialingCode: String, val fullName: String) {
    AF("AF", "+93", "Afghanistan"),
    AX("AX", "+358", "Åland Islands"),
    AL("AL", "+355", "Albania"),
    DZ("DZ", "+213", "Algeria"),
    AS("AS", "+1-684", "American Samoa"),
    AD("AD", "+376", "Andorra"),
    AO("AO", "+244", "Angola"),
    AI("AI", "+1-264", "Anguilla"),
    AQ("AQ", "+672", "Antarctica"),
    AG("AG", "+1-268", "Antigua and Barbuda"),
    AR("AR", "+54", "Argentina"),
    AM("AM", "+374", "Armenia"),
    AW("AW", "+297", "Aruba"),
    AU("AU", "+61", "Australia"),
    AT("AT", "+43", "Austria"),
    AZ("AZ", "+994", "Azerbaijan"),
    BS("BS", "+1-242", "Bahamas"),
    BH("BH", "+973", "Bahrain"),
    BD("BD", "+880", "Bangladesh"),
    BB("BB", "+1-246", "Barbados"),
    BY("BY", "+375", "Belarus"),
    BE("BE", "+32", "Belgium"),
    BZ("BZ", "+501", "Belize"),
    BJ("BJ", "+229", "Benin"),
    BM("BM", "+1-441", "Bermuda"),
    BT("BT", "+975", "Bhutan"),
    BO("BO", "+591", "Bolivia"),
    BQ("BQ", "+599", "Bonaire, Sint Eustatius and Saba"),
    BA("BA", "+387", "Bosnia and Herzegovina"),
    BW("BW", "+267", "Botswana"),
    BV("BV", "+47", "Bouvet Island"),
    BR("BR", "+55", "Brazil"),
    IO("IO", "+246", "British Indian Ocean Territory"),
    BN("BN", "+673", "Brunei"),
    BG("BG", "+359", "Bulgaria"),
    BF("BF", "+226", "Burkina Faso"),
    BI("BI", "+257", "Burundi"),
    CV("CV", "+238", "Cabo Verde"),
    KH("KH", "+855", "Cambodia"),
    CM("CM", "+237", "Cameroon"),
    CA("CA", "+1", "Canada"),
    KY("KY", "+1-345", "Cayman Islands"),
    CF("CF", "+236", "Central African Republic"),
    TD("TD", "+235", "Chad"),
    CL("CL", "+56", "Chile"),
    CN("CN", "+86", "China"),
    CX("CX", "+61", "Christmas Island"),
    CC("CC", "+61", "Cocos (Keeling) Islands"),
    CO("CO", "+57", "Colombia"),
    KM("KM", "+269", "Comoros"),
    CG("CG", "+242", "Congo"),
    CD("CD", "+243", "Congo (the Democratic Republic of the)"),
    CK("CK", "+682", "Cook Islands"),
    CR("CR", "+506", "Costa Rica"),
    CI("CI", "+225", "Côte d'Ivoire"),
    HR("HR", "+385", "Croatia"),
    CU("CU", "+53", "Cuba"),
    CW("CW", "+599", "Curaçao"),
    CY("CY", "+357", "Cyprus"),
    CZ("CZ", "+420", "Czechia"),
    DK("DK", "+45", "Denmark"),
    DJ("DJ", "+253", "Djibouti"),
    DM("DM", "+1-767", "Dominica"),
    DO("DO", "+1-809", "Dominican Republic"),
    EC("EC", "+593", "Ecuador"),
    EG("EG", "+20", "Egypt"),
    SV("SV", "+503", "El Salvador"),
    GQ("GQ", "+240", "Equatorial Guinea"),
    ER("ER", "+291", "Eritrea"),
    EE("EE", "+372", "Estonia"),
    SZ("SZ", "+268", "Eswatini"),
    ET("ET", "+251", "Ethiopia"),
    FK("FK", "+500", "Falkland Islands (Malvinas)"),
    FO("FO", "+298", "Faroe Islands"),
    FJ("FJ", "+679", "Fiji"),
    FI("FI", "+358", "Finland"),
    FR("FR", "+33", "France"),
    GF("GF", "+594", "French Guiana"),
    PF("PF", "+689", "French Polynesia"),
    TF("TF", "+262", "French Southern Territories"),
    GA("GA", "+241", "Gabon"),
    GM("GM", "+220", "Gambia"),
    GE("GE", "+995", "Georgia"),
    DE("DE", "+49", "Germany"),
    GH("GH", "+233", "Ghana"),
    GI("GI", "+350", "Gibraltar"),
    GR("GR", "+30", "Greece"),
    GL("GL", "+299", "Greenland"),
    GD("GD", "+1-473", "Grenada"),
    GP("GP", "+590", "Guadeloupe"),
    GU("GU", "+1-671", "Guam"),
    GT("GT", "+502", "Guatemala"),
    GG("GG", "+44", "Guernsey"),
    GN("GN", "+224", "Guinea"),
    GW("GW", "+245", "Guinea-Bissau"),
    GY("GY", "+592", "Guyana"),
    HT("HT", "+509", "Haiti"),
    HM("HM", "+672", "Heard Island and McDonald Islands"),
    VA("VA", "+379", "Holy See"),
    HN("HN", "+504", "Honduras"),
    HK("HK", "+852", "Hong Kong"),
    HU("HU", "+36", "Hungary"),
    IS("IS", "+354", "Iceland"),
    IN("IN", "+91", "India"),
    ID("ID", "+62", "Indonesia"),
    IR("IR", "+98", "Iran"),
    IQ("IQ", "+964", "Iraq"),
    IE("IE", "+353", "Ireland"),
    IM("IM", "+44", "Isle of Man"),
    IL("IL", "+972", "Israel"),
    IT("IT", "+39", "Italy"),
    JM("JM", "+1-876", "Jamaica"),
    JP("JP", "+81", "Japan"),
    JE("JE", "+44", "Jersey"),
    JO("JO", "+962", "Jordan"),
    KZ("KZ", "+7", "Kazakhstan"),
    KE("KE", "+254", "Kenya"),
    KI("KI", "+686", "Kiribati"),
    KW("KW", "+965", "Kuwait"),
    KG("KG", "+996", "Kyrgyzstan"),
    LA("LA", "+856", "Laos"),
    LV("LV", "+371", "Latvia"),
    LB("LB", "+961", "Lebanon"),
    LS("LS", "+266", "Lesotho"),
    LR("LR", "+231", "Liberia"),
    LY("LY", "+218", "Libya"),
    LI("LI", "+423", "Liechtenstein"),
    LT("LT", "+370", "Lithuania"),
    LU("LU", "+352", "Luxembourg"),
    MO("MO", "+853", "Macao"),
    MG("MG", "+261", "Madagascar"),
    MW("MW", "+265", "Malawi"),
    MY("MY", "+60", "Malaysia"),
    MV("MV", "+960", "Maldives"),
    ML("ML", "+223", "Mali"),
    MT("MT", "+356", "Malta"),
    MH("MH", "+692", "Marshall Islands"),
    MQ("MQ", "+596", "Martinique"),
    MR("MR", "+222", "Mauritania"),
    MU("MU", "+230", "Mauritius"),
    YT("YT", "+262", "Mayotte"),
    MX("MX", "+52", "Mexico"),
    FM("FM", "+691", "Micronesia"),
    MD("MD", "+373", "Moldova"),
    MC("MC", "+377", "Monaco"),
    MN("MN", "+976", "Mongolia"),
    ME("ME", "+382", "Montenegro"),
    MS("MS", "+1-664", "Montserrat"),
    MA("MA", "+212", "Morocco"),
    MZ("MZ", "+258", "Mozambique"),
    MM("MM", "+95", "Myanmar"),
    NA("NA", "+264", "Namibia"),
    NR("NR", "+674", "Nauru"),
    NP("NP", "+977", "Nepal"),
    NL("NL", "+31", "Netherlands"),
    NC("NC", "+687", "New Caledonia"),
    NZ("NZ", "+64", "New Zealand"),
    NI("NI", "+505", "Nicaragua"),
    NE("NE", "+227", "Niger"),
    NG("NG", "+234", "Nigeria"),
    NU("NU", "+683", "Niue"),
    NF("NF", "+672", "Norfolk Island"),
    KP("KP", "+850", "North Korea"),
    MK("MK", "+389", "North Macedonia"),
    MP("MP", "+1-670", "Northern Mariana Islands"),
    NO("NO", "+47", "Norway"),
    OM("OM", "+968", "Oman"),
    PK("PK", "+92", "Pakistan"),
    PW("PW", "+680", "Palau"),
    PS("PS", "+970", "Palestine, State of"),
    PA("PA", "+507", "Panama"),
    PG("PG", "+675", "Papua New Guinea"),
    PY("PY", "+595", "Paraguay"),
    PE("PE", "+51", "Peru"),
    PH("PH", "+63", "Philippines"),
    PN("PN", "+64", "Pitcairn"),
    PL("PL", "+48", "Poland"),
    PT("PT", "+351", "Portugal"),
    PR("PR", "+1-787", "Puerto Rico"),
    QA("QA", "+974", "Qatar"),
    RE("RE", "+262", "Réunion"),
    RO("RO", "+40", "Romania"),
    RU("RU", "+7", "Russia"),
    RW("RW", "+250", "Rwanda"),
    BL("BL", "+590", "Saint Barthélemy"),
    SH("SH", "+290", "Saint Helena, Ascension and Tristan da Cunha"),
    KN("KN", "+1-869", "Saint Kitts and Nevis"),
    LC("LC", "+1-758", "Saint Lucia"),
    MF("MF", "+590", "Saint Martin (French part)"),
    PM("PM", "+508", "Saint Pierre and Miquelon"),
    VC("VC", "+1-784", "Saint Vincent and the Grenadines"),
    WS("WS", "+685", "Samoa"),
    SM("SM", "+378", "San Marino"),
    ST("ST", "+239", "Sao Tome and Principe"),
    SA("SA", "+966", "Saudi Arabia"),
    SN("SN", "+221", "Senegal"),
    RS("RS", "+381", "Serbia"),
    SC("SC", "+248", "Seychelles"),
    SL("SL", "+232", "Sierra Leone"),
    SG("SG", "+65", "Singapore"),
    SX("SX", "+1-721", "Sint Maarten (Dutch part)"),
    SK("SK", "+421", "Slovakia"),
    SI("SI", "+386", "Slovenia"),
    SB("SB", "+677", "Solomon Islands"),
    SO("SO", "+252", "Somalia"),
    ZA("ZA", "+27", "South Africa"),
    GS("GS", "+500", "South Georgia and the South Sandwich Islands"),
    KR("KR", "+82", "South Korea"),
    SS("SS", "+211", "South Sudan"),
    ES("ES", "+34", "Spain"),
    LK("LK", "+94", "Sri Lanka"),
    SD("SD", "+249", "Sudan"),
    SR("SR", "+597", "Suriname"),
    SJ("SJ", "+47", "Svalbard and Jan Mayen"),
    SE("SE", "+46", "Sweden"),
    CH("CH", "+41", "Switzerland"),
    SY("SY", "+963", "Syria"),
    TW("TW", "+886", "Taiwan"),
    TJ("TJ", "+992", "Tajikistan"),
    TZ("TZ", "+255", "Tanzania"),
    TH("TH", "+66", "Thailand"),
    TL("TL", "+670", "Timor-Leste"),
    TG("TG", "+228", "Togo"),
    TK("TK", "+690", "Tokelau"),
    TO("TO", "+676", "Tonga"),
    TT("TT", "+1-868", "Trinidad and Tobago"),
    TN("TN", "+216", "Tunisia"),
    TR("TR", "+90", "Turkey"),
    TM("TM", "+993", "Turkmenistan"),
    TC("TC", "+1-649", "Turks and Caicos Islands"),
    TV("TV", "+688", "Tuvalu"),
    UG("UG", "+256", "Uganda"),
    UA("UA", "+380", "Ukraine"),
    AE("AE", "+971", "United Arab Emirates"),
    GB("GB", "+44", "United Kingdom"),
    US("US", "+1", "United States"),
    UM("UM", "+1", "United States Minor Outlying Islands"),
    UY("UY", "+598", "Uruguay"),
    UZ("UZ", "+998", "Uzbekistan"),
    VU("VU", "+678", "Vanuatu"),
    VE("VE", "+58", "Venezuela"),
    VN("VN", "+84", "Vietnam"),
    VG("VG", "+1-284", "Virgin Islands (British)"),
    VI("VI", "+1-340", "Virgin Islands (U.S.)"),
    WF("WF", "+681", "Wallis and Futuna"),
    EH("EH", "+212", "Western Sahara"),
    YE("YE", "+967", "Yemen"),
    ZM("ZM", "+260", "Zambia"),
    ZW("ZW", "+263", "Zimbabwe");
}
