package com.android.example.ui

enum class FieldsEnum {
    EXPANDED, SELECTEDITEM, ISSELECTIONEMPTY, EXPANDED2, SELECTEDITEM2,
    ISSELECTIONEMPTY2, PASSWORDVISIBLE1, PASSWORDVISIBLE2, PASSWORDVISIBLE3,
    ISPASSWORDVALID, PASSWORD1, PASSWORD2, PASSWORD3, ISFOCUSED1, ISFOCUSED2, ISFOCUSED3,
    ISFOCUSED4, ISFOCUSED5, ISFOCUSED6,ISFOCUSED7, ISFOCUSED8, ISFOCUSED9,
    PASSWORD, ISFOCUSED, PASSWORDVISIBLE, FIRSTNAME, LASTNAME, EMAIL,
    IDNUMBER, PHONENUMBER, DATE, FORMATEDDATE,
    EXPANDED3, SELECTEDITEM3, ISSELECTIONEMPTY3, MFAACTIVE, SHOWDIALOG, SHOWPOPUP
}