package com.android.example.ui.auctions

enum class AuctionsEnum {
    ISFOCUSED, TITLE, EXPANDCATEGORY, SELECTCATEGORY, ISCATEGORYEMTY,
    ISFOCUSED2, TITLE2, EXPANDSUBCATEGORY, SELECTSUBCATEGORY, ISSUBCATEGORYEMTY,
    DESCRIPTION, CURRENCY, CURRENCYEXPANDED, BUDGET, ISCHECKED, SELECTEDITEM, ISSELECTIONEMPTY,
    EXPANDED, PHONENUMBER


}