package com.feature.auction.ui.screen.signup

enum class FieldsEnum {
    NAME, SURNAME, LEGALNAME, IDCODE, EMAIL, PASSWORD,
    CONFIRMPASSWORD, PASSWORDVISIBLE, CONFIRMEDPASSWORDVISIBLE,
    SELECTEDITEM, EXPANDED, SELECTEDINDEX, ISCHECKED, ISNAMEVALID,
    ISSURNAMEVALID, ISLEGALNAMEEMPTY, ISIDEMPTY, ISPASSWORDVALID,
    ISCONFIRMATIONVALID, ISSELECTIONEMPTY, USERID, ROLE, ISEMAILVALID,
}